services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Web UI Master
      - "7077:7077"  # Spark Master URL
      - "4040:4040"  # App UI
    volumes:
      - ./conf:/opt/spark/conf
      - ./data:/data
      - ./scripts:/scripts
    environment:
      SPARK_MODE: master
    networks:
      - spark-net

  spark-worker-01:
    image: bitnami/spark:latest
    container_name: spark-worker-01
    hostname: spark-worker-01
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: "spark://spark-master:7077"
    networks:
      - spark-net
      
  spark-worker-02:
    image: bitnami/spark:latest
    container_name: spark-worker-02
    hostname: spark-worker-02
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: "spark://spark-master:7077"
    networks:
      - spark-net
      
  spark-worker-03:
    image: bitnami/spark:latest
    container_name: spark-worker-03
    hostname: spark-worker-03
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: "spark://spark-master:7077"
    networks:
      - spark-net

  almond:
    image: almondsh/almond:latest
    ports:
      - "8888:8888"
      - "4041:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
    networks:
      - spark-net

networks:
  spark-net:
    name: spark-network
    driver: bridge