version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "60070:50070"
    networks:
      - hadoop-net
    security_opt:
      - no-new-privileges:true

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "60075:50075"
    networks:
      - hadoop-net
    depends_on:
      - namenode
    security_opt:
      - no-new-privileges:true

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    networks:
      - hadoop-net
    security_opt:
      - no-new-privileges:true

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "60083:9083"
    networks:
      - hadoop-net
    depends_on:
      - namenode
      - datanode
      - hive-metastore-postgresql
    security_opt:
      - no-new-privileges:true

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "60100:10000"
    networks:
      - hadoop-net
    depends_on:
      - hive-metastore
    security_opt:
      - no-new-privileges:true

  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "60800:8080"
    networks:
      - hadoop-net
    depends_on:
      - hive-server
    security_opt:
      - no-new-privileges:true

volumes:
  namenode:
  datanode:

networks:
  hadoop-net:
    driver: bridge